import { ChevronLeft, ChevronRight, Check } from "lucide-react";
import { useEffect, useState } from "react";
import { getHomeSliderReports, type ResearchReport } from "@/lib/supabase/research";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

export default function HomeRecommendationCarousel() {
  const [items, setItems] = useState<ResearchReport[]>([]);
  const [active, setActive] = useState(0);
  useEffect(() => { void getHomeSliderReports().then(setItems).catch(() => setItems([])); }, []);
  useEffect(() => { if (items.length < 2) return; const timer = window.setInterval(() => setActive((i) => (i + 1) % items.length), 4500); return () => window.clearInterval(timer); }, [items.length]);
  const item = items[active];
  const change = (by: number) => setActive((i) => (i + by + items.length) % items.length);

  return <div className="relative overflow-hidden rounded-[1.5rem] border border-emerald-100/25 bg-[#071b18]/85 p-4 shadow-[var(--shadow-glow)] backdrop-blur sm:p-5">
    <div className="mb-4 flex items-center justify-between gap-3 text-[10px] font-semibold uppercase tracking-[0.08em] text-white/70 sm:text-xs"><span>Research Analyst Desk</span><span className="rounded-full bg-emerald-300/20 px-3 py-1 text-emerald-200">Selected recommendations</span></div>
    {!item ? <div className="grid min-h-80 place-items-center rounded-[1.25rem] border border-white/15 bg-[#03120f] p-8 text-center"><div><p className="font-bold text-white">Recommendations are being prepared.</p><p className="mt-2 text-xs leading-5 text-white/55">Your Research Analyst selects up to six published recommendations for this space.</p></div></div> : <>
      <article key={item.id} className="animate-rise rounded-[1.25rem] border border-white/15 bg-[#03120f] p-4"><div className="grid gap-4 sm:grid-cols-[1.1fr_0.9fr]"><div><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-widest text-white/45">{item.sector || "Equity"} research call</p><h3 className="mt-2 text-xl font-extrabold text-white">{item.company}</h3><p className="mt-1 text-xs text-white/55">{item.research_code} · {item.time_horizon || "Research view"}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold ${item.recommendation === "SELL" ? "bg-rose-400/15 text-rose-200" : "bg-emerald-400/15 text-emerald-200"}`}>{item.recommendation}</span></div><div className="mt-5 grid grid-cols-3 gap-2">{[["Entry", item.current_price], ["Target", item.target_price], ["Stop Loss", item.stop_loss]].map(([label, value]) => <div key={String(label)} className="rounded-xl bg-white/7 p-3"><p className="text-[9px] font-semibold uppercase tracking-wider text-white/45">{label}</p><p className="mt-1 text-sm font-bold text-white">{typeof value === "number" ? money.format(value) : "—"}</p></div>)}</div></div><div className="rounded-xl bg-white/7 p-4"><p className="text-[10px] font-semibold uppercase tracking-widest text-white/45">Analyst notes</p><div className="mt-3 space-y-2.5">{(item.summary || "Detailed research is available to subscribers.").split(/[.\n]/).filter(Boolean).slice(0, 3).map((note, i) => <div key={i} className="flex gap-2 text-xs leading-5 text-white/75"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-300" /><span>{note.trim()}</span></div>)}</div><div className="mt-4 rounded-xl border border-amber-200/20 bg-amber-300/10 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-amber-200">Risk level</p><p className="mt-1 text-base font-bold text-white">{item.risk || "Moderate"}</p></div></div></div></article>
      {items.length > 1 && <div className="mt-3 flex items-center justify-between"><div className="flex gap-1.5">{items.map((entry, i) => <button key={entry.id} type="button" onClick={() => setActive(i)} aria-label={`Show recommendation ${i + 1}`} className={`h-1.5 rounded-full ${i === active ? "w-5 bg-emerald-300" : "w-1.5 bg-white/35"}`} />)}</div><div className="flex gap-1"><button type="button" onClick={() => change(-1)} className="rounded-full p-1.5 text-white/70 hover:bg-white/10" aria-label="Previous"><ChevronLeft className="h-4 w-4" /></button><button type="button" onClick={() => change(1)} className="rounded-full p-1.5 text-white/70 hover:bg-white/10" aria-label="Next"><ChevronRight className="h-4 w-4" /></button></div></div>}
    </>}
  </div>;
}
